### ISSUE TITLE
ABAC auth mode not working

### ISSUE THREAD

**Issue by BastiPaeltz** [pawankkamboj/HA-kubernetes-ansible#19]
Hey,

first of all thanks for this great repository, I was really lost in setting up HA Kubernetes until I found this, so thanks a lot.

I did set up Vagrant using the provided Vagrantfile however after the deployment the cluster did not came up. I checked the kubelet logs and it was filled with error messages like this one.

`kubelet_node_status.go:98] Unable to register node "master2" with API server: the server does not allow access to the requested resource (post nodes)`

I changed the `auth_mode` variable to `AlwaysAllow` and afterwards the cluster was working. So I think this is related to ABAC.

**Comment by pawankkamboj** [comment]
Yes, it was related to ABAC, will modify kube config file and include user
context as of now user SSL cert to connect API

**Comment by dsever** [comment]
Hi,

Had the same issue but fixed it manually by creating user certificate (dirty workaround, should be included in ansible playbook):

```
kubeletconfig config:
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.pem
    server: https://x.x.x.x
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet-devmaster
  name: kubelet-devmaster@kubernetes
current-context: kubelet-devmaster@kubernetes
kind: Config
users:
- name: kubelet-devmaster
  user:
    client-certificate: /etc/kubernetes/pki/kubelet-devmaster.crt
    client-key: /etc/kubernetes/pki/kubelet-devmaster.key

```

 


And create user certificate like, using ansible machine and CA certificates created earlier:
```
openssl genrsa -out kubelet-devmaster.key 2048
openssl req -new -key kubelet-devmaster.key -out kubelet-devmaster.csr -subj "/CN=kubelet-devmaster" -config $SSL_CONFIG
openssl x509 -req -in kubelet-devmaster.csr  -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out kubelet-devmaster.crt -days 365 -extensions v3_req -extfile $SSL_CONFIG

```
And finally update policy file by adding line:

`{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"kubelet-devmaster","namespace": "*",              "resource": "*"}}`

But after some investigation, can you clear to me what was idea for the users:
kubelet-devmaster, probably for inter cluster communication?
kube-admin, for admin access to cluster?

And can you provide me one hint: what's the right way to restart kube-api containe, to collect new policies?

Dubravko
